# Generated by Django 5.2.1 on 2025-06-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_action_created_at_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='target_user',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
